///////////////////////////////////////////////////////////////////////////////////////////
// This file is automatically generated.
// Modifying it is not recommended.
///////////////////////////////////////////////////////////////////////////////////////////
namespace ProjectOrigin
{
    /// <summary>
    /// Resolution level enumeration
    /// </summary>
    /// <remarks>
    /// 解像度レベルの列挙型
    /// </remarks>
    public enum ResolutionLevel : uint
    {
        Lowest = 0,
        Normal = 1,
        High = 2,
        Highest = 3,
    }
}
