///////////////////////////////////////////////////////////////////////////////////////////
// This file is automatically generated.
// Modifying it is not recommended.
///////////////////////////////////////////////////////////////////////////////////////////
using ADONEGames.ResolutionCalcCache;

namespace ProjectOrigin
{
    /// <summary>
    /// Serializable resolution data
    /// </summary>
    public struct ResolutionData : IResolutionData
    {
        /// <inheritdoc /> 
        int IResolutionData.Width => 1080;

        /// <inheritdoc />
        int IResolutionData.Height => 1920;
    }
}
