///////////////////////////////////////////////////////////////////////////////////////////
// This file is automatically generated.
// Modifying it is not recommended.
///////////////////////////////////////////////////////////////////////////////////////////
namespace ProjectOrigin
{
    /// <summary>
    /// Resolution Category setting
    /// </summary>
    /// <remarks>
    /// 解像度カテゴリの設定
    /// </remarks>
    public enum ResolutionCategory : uint
    {
        Base = 0,
        InGame = 1,
        OutGame = 2,
    }
}
